CREATE TABLE metricas_snapshots (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nivel ENUM('account','campaign','adset','ad') NOT NULL,
    entidad_id INT UNSIGNED NOT NULL,
    meta_entidad_id VARCHAR(50) NOT NULL,
    fecha DATE NOT NULL,
    gasto DECIMAL(15,2) NOT NULL DEFAULT 0,
    impresiones BIGINT UNSIGNED NOT NULL DEFAULT 0,
    alcance BIGINT UNSIGNED NOT NULL DEFAULT 0,
    frecuencia DECIMAL(8,4) NULL,
    clicks_totales BIGINT UNSIGNED NOT NULL DEFAULT 0,
    clicks_enlace BIGINT UNSIGNED NOT NULL DEFAULT 0,
    ctr DECIMAL(8,4) NULL,
    cpc DECIMAL(15,4) NULL,
    cpm DECIMAL(15,4) NULL,
    costo_por_resultado DECIMAL(15,4) NULL,
    resultados BIGINT UNSIGNED NULL,
    conversiones BIGINT UNSIGNED NULL,
    metricas_extendidas JSON NULL,
    importado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_snapshot_unico (nivel, entidad_id, fecha),
    KEY idx_snapshot_meta_id_fecha (nivel, meta_entidad_id, fecha),
    KEY idx_snapshot_fecha (fecha)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE importaciones_meta (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cuenta_publicitaria_id INT UNSIGNED NOT NULL,
    usuario_id INT UNSIGNED NOT NULL,
    rango_inicio DATE NOT NULL,
    rango_fin DATE NOT NULL,
    estado ENUM('en_curso','completada','fallida') NOT NULL DEFAULT 'en_curso',
    iniciado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalizado_en DATETIME NULL,
    campanias_afectadas INT UNSIGNED NOT NULL DEFAULT 0,
    adsets_afectados INT UNSIGNED NOT NULL DEFAULT 0,
    anuncios_afectados INT UNSIGNED NOT NULL DEFAULT 0,
    snapshots_afectados INT UNSIGNED NOT NULL DEFAULT 0,
    llamadas_meta INT UNSIGNED NOT NULL DEFAULT 0,
    error_mensaje TEXT NULL,
    log_resumen JSON NULL,
    KEY idx_imp_cuenta_fecha (cuenta_publicitaria_id, iniciado_en),
    CONSTRAINT fk_imp_cuenta FOREIGN KEY (cuenta_publicitaria_id) REFERENCES cuentas_publicitarias(id) ON DELETE CASCADE,
    CONSTRAINT fk_imp_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
